controllers:
    resource: ../src/Controller/**/*
    type: attribute
    exclude: ../src/Controller/ApiWp

apis_wp:
    resource: ../src/Controller/ApiWp
    type: attribute
    prefix: '/api/wp'
    name_prefix: 'app_api_wp_'
